apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devvault-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: devvault.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: devvault-backend-service
            port:
              number: 5000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devvault-frontend-service
            port:
              number: 80
